version: '3'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "4000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
