version: '3'

services:
  frontend:
    image: my-react-app
    build:
      context: ./client # Path to your React app directory
    ports:
      - "4000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./server # Path to your Node.js app directory
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
